# Google Cloud Build configuration for Care Connect
# Client: blue cross home care ltd
# GCP quota-compliant multi-container architecture

steps:
  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'frontend/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-frontend:$SHORT_SHA', '.']
    
  # Build backend image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'backend/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-backend:$SHORT_SHA', '.']
    
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-frontend:$SHORT_SHA']
    
  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-backend:$SHORT_SHA']
    
  # Terraform init
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init
        
  # Terraform plan
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform plan \
          -var="project_id=$PROJECT_ID" \
          -var="client_name=bluecrosshomecareltd" \
          -var="frontend_image=gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-frontend:$SHORT_SHA" \
          -var="backend_image=gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-backend:$SHORT_SHA" \
          -var="db_password=${_DB_PASSWORD}" \
          -var="jwt_secret=${_JWT_SECRET}" \
          -var="license_key=${_LICENSE_KEY}"
        
  # Terraform apply
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform apply -auto-approve \
          -var="project_id=$PROJECT_ID" \
          -var="client_name=bluecrosshomecareltd" \
          -var="frontend_image=gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-frontend:$SHORT_SHA" \
          -var="backend_image=gcr.io/$PROJECT_ID/careconnect-bluecrosshomecareltd-backend:$SHORT_SHA" \
          -var="db_password=${_DB_PASSWORD}" \
          -var="jwt_secret=${_JWT_SECRET}" \
          -var="license_key=${_LICENSE_KEY}"

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Substitutions
substitutions:
  _DB_PASSWORD: '.p173bn2a9ui'
  _JWT_SECRET: '0.75bi85jrq1t'
  _LICENSE_KEY: '8e30afee-7c07-424d-8a59-6e735eaaaf77'

# Build timeout
timeout: '1800s'